name: vcs_hackathon
description: "Nguoi Bat Trang AI Chatbot"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  chatview: 2.4.0
  sqflite: 2.4.1
  path: 1.9.0
  google_fonts: ^6.2.1
  envied: ^1.0.0

dependency_overrides:
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^1.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  fonts:
    - family: FSPFBeauSansPro
      fonts:
        - asset: assets/fonts/FSPFBeauSansPro-Regular.ttf
        - asset: assets/fonts/FSPFBeauSansPro-Thin.ttf
        - asset: assets/fonts/FSPFBeauSansPro-Bold.ttf